
server:
    port: 8083

spring:
  application:
    name: reviewsms
  config:
    import: optional:configserver:http://localhost:8080
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5434/review_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123


eureka:
  client:
    serviceUrl:
        defaultZone: http://servicereg:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true


    # ** Zepkin Configuration **

    #it traces all the requests and it could be changed to 0.6 in prod environment


management:
  tracing:
    sampling:
        probability: 1.0
  zipkin:
    base-url: http://localhost:9411/



